# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: /home/delorenj/code/pjangler/templates/commonproject
project_description: 
project_name: Tiller Mcp Server
ticket_provider: plane
